image: gradle:alpine

stages:
  - build

compile:
  stage: build
  script:
    - gradle compileJava

delombok:
  stage: build
  script:
    - gradle delombok
  artifacts:
    paths:
      - build/delombok/**
